baseURL = "https://www.innervoicepower.com"
languageCode = "en-us"
title = "Inner Voice Coaching"
disableKinds = ["taxonomy"]
enableRobotsTXT = "true"
summaryLength = 30
copyright = "BÃ©a Beaudry"
[params]
  description = "Where Your Power Resides"
  logo = "android-chrome-192x192.png"
  donation_url = ""
  contact = ""
  copyrighturl = "https://www.innervoicepower.com"
  address1 = ""
  address2 = ""