baseURL = "https://www.innervoicepower.com"
languageCode = "en-us"
title = "Inner Voice Coaching"
disableKinds = ["taxonomy"]
enableRobotsTXT = "true"
summaryLength = 30
copyright = "BÃ©a Beaudry"
[params]
  description = "Where you power resides"
  donation_url = ""
  contact = "bkbeaudry@gmail.com"
  copyrighturl = "https://www.innervoicepower.com"
  address1 = ""
  address2 = ""